ENH: adding self-contained test and test data
Currently, the test is failing, since apparently some settings are mandatory.
This needs to be clarified in the docs.

/Users/fedorov/github/radiomics-platform/RadiomicsPlatform
Traceback (most recent call last):
  File "Examples/helloRadiomics.py", line 32, in <module>
      rpp.ComputeRadiomicsFeatures()
        File "/Users/fedorov/github/radiomics-platform/RadiomicsPlatform/RadiomicsPlatform/RadiomicsPreProcessingLib/RadiomicsPreProcessing.py", line 101, in ComputeRadiomicsFeatures
            self.RadiomicsFeatureVector.update( self.generalFeatures.EvaluateFeatures() )
              File "/Users/fedorov/github/radiomics-platform/RadiomicsPlatform/RadiomicsPlatform/RadiomicsFeaturesLib/Radiomics_General/Radiomics_General.py", line 32, in EvaluateFeatures
                  self.radiomics_general_FeatureVector[feature] = eval(self.radiomics_general_FeatureVector[feature])
                    File "<string>", line 1, in <module>
                      File "/Users/fedorov/github/radiomics-platform/RadiomicsPlatform/RadiomicsPlatform/RadiomicsFeaturesLib/Radiomics_General/Radiomics_General_Features.py", line 30, in patientID
                          return(Settings["patientid"])
                          KeyError: 'patientid'